### ISSUE TITLE
Facebook connect

### ISSUE THREAD

**Issue by cmdcmdcmd** [openwhyd/openwhyd-electron#9]
Facebook connect doesn't seems to be working

**Comment by adrienjoly** [comment]
Good catch, Claire! 👍

**Comment by adrienjoly** [comment]
WIP:

- intercepting Facebook connect, to redirect to `https://www.facebook.com/connect/login_success.html` (https://discuss.atom.io/t/connecting-to-the-facebook-api-from-electron/22413/8)
- following that tutorial: https://competenepal.com/lets-make-a-facebook-login-system-in-electron-that-actually-works/
- and facebook's reference documentation: https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

**Comment by adrienjoly** [comment]
Didn't test account creation (sign up) with Facebook, tho.
